# 在 main 分支触发提交且提交的 message 发布到npm
name: publish to npm
on:
  push:
    branches: [main]

jobs:
  pub:
    name: build and  publish to npm
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    if: contains(github.event.head_commit.message, 'version')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: |
          npm ci

      - name: Build package
        run: |
          npm run build

      - name: publish to npm with Provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd dist
          npm publish --provenance --access public
